source 'https://bitbucket.org/int123c/specs.git'
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '10.0'
use_frameworks!

def sharedPods
    pod 'Cloudability', :path => '../'
end

target 'Cloudability_Example' do
  sharedPods
end
