source 'https://bitbucket.org/int123c/specs.git'
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '10.0'
use_frameworks!

target 'Cloudability_Example' do
  pod 'Cloudability', :path => '../'

  target 'Cloudability_Tests' do
    inherit! :search_paths
    
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '4.0'
    end
  end
end